import 'package:freezed_annotation/freezed_annotation.dart';

/// Data Transfer Object for the BSMLogin API request.
/// BSMLogin(Token, UserId, PW, DeviceId, GeoLat, GeoLong, ActionDte, WC)

part 'login_request.freezed.dart';
part 'login_request.g.dart';

@freezed
class LoginRequest with _$LoginRequest {
  const factory LoginRequest({
    /// The API parameter is 'Token'. For initial login, this is empty.
    @JsonKey(name: 'Token') String? token,

    /// The API parameter is 'UserId'. Maps to our domain 'userId'.
    @JsonKey(name: 'UserId') required String userId,

    /// The API parameter is 'PW'. Never log this value.
    @JsonKey(name: 'PW') required String password,

    /// The API parameter is 'DeviceId'.
    @JsonKey(name: 'DeviceId') required String deviceId,

    /// The API parameter is 'GeoLat'. Nullable per spec.
    @JsonKey(name: 'GeoLat') String? geoLat,

    /// The API parameter is 'GeoLong'. Nullable per spec.
    @JsonKey(name: 'GeoLong') String? geoLong,

    /// The API parameter is 'ActionDte'. ISO8601 format.
    @JsonKey(name: 'ActionDte') required String actionDate,

    /// The API parameter is 'WC'. Work Code, empty for login.
    @JsonKey(name: 'WC') String? workCode,
  }) = _LoginRequest;

  /// Factory constructor from JSON map.
  /// Generated by json_serializable in login_request.g.dart
  factory LoginRequest.fromJson(Map<String, dynamic> json) =>
      _$LoginRequestFromJson(json);
}
